### ISSUE TITLE
Broken filename alignment in explorer

### ISSUE THREAD

**Issue by davidedellagiustina** [FlorianWoelki/obsidian-iconize#263] opened 2023-10-02 20:39 UTC
**Describe the bug**
Apparently, sometimes the alignment of files without an icon breaks in the file explorer (see screenshot below).

**To Reproduce**
I cannot reproduce this deterministically, but the following _sometimes_ works:
1. create some note in a folder;
2. close vault and Obsidian;
3. re-open vault;
4. create some other note;
5. newly created note seems to be more indented than the one created before.

**Expected behavior**
Consistent alignment even if no icon / inheris icon is selected.

**Screenshots**
![immagine](https://github.com/FlorianWoelki/obsidian-iconize/assets/22601842/4caeeec4-dc9a-4b42-b7cb-47b081276166)

**Comment by FlorianWoelki** [comment] 2023-10-03 08:20
I cannot reproduce this in any way.

If you say that there does no icon exists for the note, then I don't think it is a problem with Iconize because it doesn't change any styling of the notes without icons.

**Comment by davidedellagiustina** [comment] 2023-10-03 10:32
@FlorianWoelki That's also an option, but disabling the Iconize plugin immediately fixes it.

If it helps in trying to reproduce, the `Templates` folder in my screenshot was inside some other top-level folder with no icon either. I'll try to gether more info an the problem later today.

**Comment by davidedellagiustina** [comment] 2023-10-03 12:35
I investigated a bit more and here's what I found:
- apparently, I am only able to reproduce for notes inside my `Templates` folder, which is itself nested inside a `Schema` folder;
- the same happens if there are notes with icons in the same folder (see picture below, where `Thing 1` was created before reloading Obsidian, and `Thing 2` was created after the reload);
- the "longer" indentation also happens after removing some an icon from a note file;
- I re-tried disabling Iconize, and actually it does **not** fix the issue, I have no idea why it looked like it did last time I checked.

![immagine](https://github.com/FlorianWoelki/obsidian-iconize/assets/22601842/110533e5-9801-4d28-8780-eb97ac2a294d)

Is anybody else able to reproduce? I'm on Obsidian 1.4.14, installer 1.4.13 (might update it later just ot check).

**Comment by FlorianWoelki** [comment] 2023-10-03 12:59
> I investigated a bit more and here's what I found:
> 
> * apparently, I am only able to reproduce for notes inside my `Templates` folder, which is itself nested inside a `Schema` folder;
> * the same happens if there are notes with icons in the same folder (see picture below, where `Thing 1` was created before reloading Obsidian, and `Thing 2` was created after the reload);
> * the "longer" indentation also happens after removing some an icon from a note file;
> * I re-tried disabling Iconize, and actually it does **not** fix the issue, I have no idea why it looked like it did last time I checked.
> 
> ![immagine](https://user-images.githubusercontent.com/22601842/272258459-110533e5-9801-4d28-8780-eb97ac2a294d.png)
> 
> Is anybody else able to reproduce? I'm on Obsidian 1.4.14, installer 1.4.13 (might update it later just ot check).

So I'll close the issue for now, because it does not relate to Iconize.

**Closed by FlorianWoelki** 2023-10-03 12:59 UTC
Labels: question
