### ISSUE TITLE
Iconize 2.11.9 conflicts with windows icons and Metabind

### ISSUE THREAD

**Issue by Davve37** [FlorianWoelki/obsidian-iconize#438] opened 2024-04-08 07:22 UTC
**Describe the bug**
Iconize conflicts with windows 11 icons and cause lines where they exist to fail. It also disrupt some Metabind fields.

**To Reproduce**
1. Enable iconize 2.11.9
2. Go to note with windows 11 icons
3. ???

**Expected behavior**
What I expected: 
https://i.imgur.com/wwLGZTF.png
https://i.imgur.com/oaD8AGD.png

**Screenshots**
What I got:
https://i.imgur.com/ry8o1tC.png
https://i.imgur.com/goSQEgg.png

**Additional context**

**Comment by mayeenulislam** [comment] 2024-04-08 13:18
I'm having a similar issue.
Any icon that is not within Iconize's radar is getting omitted from view in Editing mode.
But they are working in the Reading mode.

For example, my note has a hand emoji like: 👆, which was added using the Mac Emoji picker, which is behaving like this.
But if I want to pick the same emoji using `:` notation, it's not within the list of Icons.

I'm using Font Awesome Solid and Lucide Icons and for Emoji Style my choice is "Native"

**Comment by mayeenulislam** [comment] 2024-04-08 13:33
It's only for Emojis. When the cursor is on that line, it's visible, like below<br/>
<img width="313" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/4551598/1e5c5211-32f3-43df-a0cc-d82ca8fd5ace">

But when the cursor is out:<br/>
<img width="175" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/4551598/f0b4858c-11d8-4dce-bafa-82fce4189e3d">

I tried changing Emoji Style to "Twimoji" and Force Reload Obsidian<br/>
Then "None" and Force Reload.

The issue persists.

The Emojis only works fine when the Iconize is inactive (even without Force Reload)

**Comment by mayeenulislam** [comment] 2024-04-08 13:40
I'm afraid it's affecting the Bulleted List as well. Iconize v2.11.9.

When Iconize is active:
<img width="168" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/4551598/5ea787a2-6f55-4e6d-9bf9-88c55368cdd4">

When inactive:
<img width="178" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/4551598/2c1da21b-a888-42ff-bc9a-bde8151735a4">

**Comment by FlorianWoelki** [comment] 2024-04-08 13:42
> It's only for Emojis. When the cursor is on that line, it's visible, like below<br/>
> 
> <img width="313" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/4551598/1e5c5211-32f3-43df-a0cc-d82ca8fd5ace">
> 
> 
> 
> But when the cursor is out:<br/>
> 
> <img width="175" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/4551598/f0b4858c-11d8-4dce-bafa-82fce4189e3d">
> 
> 
> 
> I tried changing Emoji Style to "Twimoji" and Force Reload Obsidian<br/>
> 
> Then "None" and Force Reload.
> 
> 
> 
> The issue persists.
> 
> 
> 
> The Emojis only works fine when the Iconize is inactive (even without Force Reload)

what about having emojis set to native and then force reload?

**Comment by Davve37** [comment] 2024-04-08 13:48
> what about having emojis set to native and then force reload?

That helps a bit however it still destroys dataview tables when windows icons appear inside the dataview table.

https://i.imgur.com/kGOKCmW.png

**Comment by mayeenulislam** [comment] 2024-04-08 14:00
My Emoji Style is "Native", it's the same.

However found a new bug using `:FasAnglesUp:` into the note:
<img width="175" alt="image" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/4551598/f0b4858c-11d8-4dce-bafa-82fce4189e3d">

When Iconize is active, opening the note by clicking on the title from Explorer giving an error:
> 🔴  Failed to load "MyNote.md". Ranges must be added sorted by 'from' position and 'startSide'

**Comment by I-Pch** [comment] 2024-04-08 14:13
> My Emoji Style is "Native", it's the same.
> 
> However found a new bug using `:FasAnglesUp:` into the note: <img alt="image" width="175" src="https://private-user-images.githubusercontent.com/4551598/320500647-f0b4858c-11d8-4dce-bafa-82fce4189e3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODUyOTgsIm5iZiI6MTcxMjU4NDk5OCwicGF0aCI6Ii80NTUxNTk4LzMyMDUwMDY0Ny1mMGI0ODU4Yy0xMWQ4LTRkY2UtYmFmYS04MmZjZTQxODllM2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMTQwMzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGU4YWRiYzFkNDZjMzdlZWE2NjBmMWY3Mjc4MzM3ZGRlNTRlZDFmZWI1MDVkNjZkMTc5ZmU3MzhmOWE4OThkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZfPvYoYQviHbQI40zUrZMxh5O7hLWS-RApepzmyt43I">
> 
> When Iconize is active, opening the note by clicking on the title from Explorer giving an error:
> 
> > 🔴  Failed to load "MyNote.md". Ranges must be added sorted by 'from' position and 'startSide'

Makes me think about was I was seeing with Iconize 2.11.7, yesterday -> https://github.com/FlorianWoelki/obsidian-iconize/issues/412#issuecomment-2041507548 (only tested with emojis/twemojis though) which I think I still get with Iconize 2.11.9 (but I didn't got the opportunity to properly test this yet)

**Comment by schemen** [comment] 2024-04-08 18:07
Same error here: bullet points are being lost

**Comment by FlorianWoelki** [comment] 2024-04-08 18:21
would it be possible for someone to give me a minimal reproduction example. especially if it is affecting dataview + iconize the specific dataview query.

**Comment by Caotenhoch2** [comment] 2024-04-08 18:44
Use [this](https://github.com/FlorianWoelki/obsidian-iconize/files/14909889/Untitled.md) example file with the following query:
```
TABLE choice(test, "☑", "☐") as "test"
FROM "Test"
```
This results in the emoji being listed as "null"
![grafik](https://github.com/FlorianWoelki/obsidian-iconize/assets/65490656/12599554-8472-4f52-9907-159277cfb5e6)

**Comment by primarist** [comment] 2024-04-08 20:10
I'm also experiencing this but with the Tasks plugin. Tasks uses emojis to indicate different due dates, priorities, etc. The emojis are only visible when the cursor is placed in the line containing the emoji, but when you select a different line, the emoji disappears. Additionally, when that task is queried using Dataview, the emoji is replaced by the text "null".

**Comment by dkadev** [comment] 2024-04-08 20:49
I'm experiencing this with inline emojis on macOS, I can see them in source mode but as soon as I change to read mode emoji is replaced with "null".
Disabling iconize plugin stops this behaviour. Happening since I updated today.
I have another vault with outdated version 2.11.4 and bug does not exist.

**Comment by I-Pch** [comment] 2024-04-08 20:59
> would it be possible for someone to give me a minimal reproduction example. especially if it is affecting dataview + iconize the specific dataview query.

As a very minimal repro, I have this query : 

This doesn't work and in fact breaks as soon as I add the `:sparkles:` emoji 😊 
The issue seem to be linked to having a query within a callout + at least one emoji (didn't test with icons)
```
> [!NOTE] Title
> ✨
> ```dataview
> TABLE file.ctime AS "Created"
> FROM "Test"
> SORT file.ctime DESC
> ```
``` 

While this query still works as expected : 
```
> [!NOTE] Title
> 
> ```dataview
> TABLE file.ctime AS "Created"
> FROM "Test"
> SORT file.ctime DESC
> ```
``` 

In the screenshot below, the 3 Dataview queries are the same as the ones I shared here, just placed in different context 😊 .
<img width="850" alt="Dataview Iconize" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/77828085/2b7183f5-f136-42b6-ac3b-7f73dfb35f7d">

I have only 14 notes in the vault I'm using to test the emojis issues 😊 and only 2 plugins (Dataview and Iconize).
I'm on Mac (Big Sur 11.7.10) + Obsidian 1.5.12 and my vault is stored on and sync through iCloud. 
I only use the default Obsidian Dark Theme and have no CSS snippets.

**Comment by ollecello** [comment] 2024-04-09 05:10
I've the same massive problem on all levels.

**Comment by FlorianWoelki** [comment] 2024-04-09 06:14
> > would it be possible for someone to give me a minimal reproduction example. especially if it is affecting dataview + iconize the specific dataview query.
> 
> As a very minimal repro, I have this query :
> 
> ```
> > [!NOTE] Title
> > ✨
> > ```dataview
> > TABLE file.ctime AS "Created"
> > FROM "Test"
> > SORT file.ctime DESC
> > ```
> ```
> 
> This 👆 doesn't work and in fact breaks as soon as I add the `:sparkles:` emoji 😊 The issue seem to be linked to having a query within a callout + at least one emoji/icon ~(didn't test with icons)~
> 
> While this query still works as expected :
> 
> ```
> > [!NOTE] Title
> > 
> > ```dataview
> > TABLE file.ctime AS "Created"
> > FROM "Test"
> > SORT file.ctime DESC
> > ```
> ```
> 
> In the screenshot below, the 3 Dataview queries are the same as the ones I shared here, just placed in different context 😊 . <img alt="Dataview Iconize" width="850" src="https://private-user-images.githubusercontent.com/77828085/320645084-2b7183f5-f136-42b6-ac3b-7f73dfb35f7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDM0NDIsIm5iZiI6MTcxMjY0MzE0MiwicGF0aCI6Ii83NzgyODA4NS8zMjA2NDUwODQtMmI3MTgzZjUtZjEzNi00MmI2LWFjM2ItN2Y3M2RmYjM1ZjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhOWYzYjU2ZmQ5YzYwMjczMTgzODc2NWExZTVhNGM5MmI5NzQ3ZGY4OGFhMmZkZDI3YzZmNTY1OGZjMGVhYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VOs7Skfx4zrlDclPVqFpwR_elyRpoKeN0wLUv8rb-yU">
> 
> Edit: Same result using just `:LiSparkles:` (from `Lucide`)
> 
> <img alt="Iconize - Dataview - Lucide Icon " width="832" src="https://private-user-images.githubusercontent.com/77828085/320651353-0d983f30-2035-4584-af03-61c759d62fe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDM0NDIsIm5iZiI6MTcxMjY0MzE0MiwicGF0aCI6Ii83NzgyODA4NS8zMjA2NTEzNTMtMGQ5ODNmMzAtMjAzNS00NTg0LWFmMDMtNjFjNzU5ZDYyZmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlOTE3NWNhZDlkZGE1ZDkzM2MzM2U1MGM4MmFjNDk4YjkyMTJmZGYwZTU1OGY2NDRhYTdjZTJmNmU2YWRlZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RBFhl-vkOyY3XwYM2bO2EkYsL7TX_np5UjEGhuhme2o">
> I have only 14 notes in the vault I'm using to test the emojis issues 😊 and only 2 plugins (Dataview and Iconize 2.11.9). I'm on Mac (Big Sur 11.7.10) + Obsidian 1.5.12 and my vault is stored on and sync through iCloud. I only use the default Obsidian Dark Theme and have no CSS snippets.
> 
> Edit: Adding a very small screen-recording where all I do to break the Dataview query is adding an emoji ...
> 
>  Iconize.Dataview.-.Callout.-.Emoji.mov 
> I hope this helps 😊

thank you! this really helped and i was able to reproduce it.

**Comment by FlorianWoelki** [comment] 2024-04-09 07:30
just fyi: i have a working solution, just need to adjust the code a bit and adapt it to icons as well. i'll keep you updated here.

**Comment by FlorianWoelki** [comment] 2024-04-10 06:36
hey there,

I've pushed a commit to fix the latest issues. at least I am not able to reproduce any issue related to that anymore. could someone please check out the latest code and see if it works for them?

**Comment by I-Pch** [comment] 2024-04-10 07:26
> hey there,
> 
> I've pushed a commit to fix the latest issues. at least I am not able to reproduce any issue related to that anymore. could someone please check out the latest code and see if it works for them?

Sorry for my potential ignorant comment but don't you need to release a new version for us to test ? 🙈 
... or is there a specific process to follow ? (manual install maybe ?)

**Comment by mProjectsCode** [comment] 2024-04-10 14:37
You could setup beta releases with BRAT for this. That would allow users to download beta versions via BRAT, without pushing out beta releases to all users. I do that for almost all of my plugins.

**Comment by CoachKidd** [comment] 2024-04-11 08:26
I've got this issue too... Thanks for taking a look at it... Is there a release date for it yet?

**Comment by FlorianWoelki** [comment] 2024-04-11 08:31
probably this weekend.

**Comment by CoachKidd** [comment] 2024-04-11 11:38
> probably this weekend.

That's awesome news, thanks!

As an end user of Obsidian (my days of being a competent coder are long gone) are there any user tests I can do that would be helpful for you?

**Comment by FlorianWoelki** [comment] 2024-04-11 11:51
> You could setup beta releases with BRAT for this. That would allow users to download beta versions via BRAT, without pushing out beta releases to all users. I do that for almost all of my plugins.

yeah so I should setup BRAT in the future, thank you for the suggestion!



> > probably this weekend.
> 
> That's awesome news, thanks!
> 
> As an end user of Obsidian (my days of being a competent coder are long gone) are there any user tests I can do that would be helpful for you?

sure! because BRAT (or something similar) is not embedded yet, you can copy and paste the `main.js` file to the Iconize plugin (sorry I cannot upload the file directly). [This is the link](https://drive.google.com/file/d/11VK1xAGDFQt7eOlCiTe4Nw2SjHXk95_V/view?usp=sharing).

These are the steps you need to follow:
1. Quit Obsidian entirely
2. Go to your Vault's directory (where you see the `.obsidian` directory)
3. Go to: `/.obsidian/plugins/obsidian-iconize (or obsidian-icon-folder)/`
4. Paste the downloaded `main.js` file into this directory

Then, hopefully, things will work.

**Comment by CoachKidd** [comment] 2024-04-11 12:06
Thanks @FlorianWoelki ... It works perfectly for me.

Do you have a "Buy me a coffee" link?

**Comment by I-Pch** [comment] 2024-04-11 14:12
> > You could setup beta releases with BRAT for this. That would allow users to download beta versions via BRAT, without pushing out beta releases to all users. I do that for almost all of my plugins.
> 
> yeah so I should setup BRAT in the future, thank you for the suggestion!
> 
> > > probably this weekend.
> > 
> > 
> > That's awesome news, thanks!
> > As an end user of Obsidian (my days of being a competent coder are long gone) are there any user tests I can do that would be helpful for you?
> 
> sure! because BRAT (or something similar) is not embedded yet, you can copy and paste the `main.js` file to the Iconize plugin (sorry I cannot upload the file directly). [This is the link](https://drive.google.com/file/d/11VK1xAGDFQt7eOlCiTe4Nw2SjHXk95_V/view?usp=sharing).
> 
> These are the steps you need to follow:
> 
> 1. Quit Obsidian entirely
> 2. Go to your Vault's directory (where you see the `.obsidian` directory)
> 3. Go to: `/.obsidian/plugins/obsidian-iconize (or obsidian-icon-folder)/`
> 4. Paste the downloaded `main.js` file into this directory
> 
> Then, hopefully, things will work.

Thank you for sharing the file 😄 !

I just ran some tests (in the same vault I used before) and it's way better from my side of the screen 😊 : 

I was able to: 
- Have Dataview queries in a callout + icon/emoji but only if I used `Native` emojis (using Twemojis, apparently lead to the freezing of the whole vault 🤷‍♀️ ... where all I could do was scroll through the specific note I used for testing purpose here > https://github.com/FlorianWoelki/obsidian-iconize/issues/438#issuecomment-2043632899.
I had to delete the `workspace.json` to solve the issue (because the vault would open on the note that broke it 😅 , so rebooting wasn't enough 😇 )
- Open notes in a split view 🎉 !!! 

Emojis still seems to render when "they want to" in Live Preview 😊  (https://github.com/FlorianWoelki/obsidian-iconize/issues/438#issuecomment-2042773836)

**Comment by FlorianWoelki** [comment] 2024-04-11 15:58
> > > You could setup beta releases with BRAT for this. That would allow users to download beta versions via BRAT, without pushing out beta releases to all users. I do that for almost all of my plugins.
> > 
> > 
> > yeah so I should setup BRAT in the future, thank you for the suggestion!
> > > > probably this weekend.
> > > 
> > > 
> > > That's awesome news, thanks!
> > > As an end user of Obsidian (my days of being a competent coder are long gone) are there any user tests I can do that would be helpful for you?
> > 
> > 
> > sure! because BRAT (or something similar) is not embedded yet, you can copy and paste the `main.js` file to the Iconize plugin (sorry I cannot upload the file directly). [This is the link](https://drive.google.com/file/d/11VK1xAGDFQt7eOlCiTe4Nw2SjHXk95_V/view?usp=sharing).
> > These are the steps you need to follow:
> > 
> > 1. Quit Obsidian entirely
> > 2. Go to your Vault's directory (where you see the `.obsidian` directory)
> > 3. Go to: `/.obsidian/plugins/obsidian-iconize (or obsidian-icon-folder)/`
> > 4. Paste the downloaded `main.js` file into this directory
> > 
> > Then, hopefully, things will work.
> 
> Thank you for sharing the file 😄 !
> 
> I just ran some tests (in the same vault I used before) and it's way better from my side of the screen 😊 :
> 
> I was able to:
> 
> * Have Dataview queries in a callout + icon/emoji but only if I used `Native` emojis (using Twemojis, apparently lead to the freezing of the whole vault 🤷‍♀️ ... where all I could do was scroll through the specific note I used for testing purpose here > [Iconize 2.11.9 conflicts with windows icons and Metabind #438 (comment)](https://github.com/FlorianWoelki/obsidian-iconize/issues/438#issuecomment-2043632899).
>   I had to delete the `workspace.json` to solve the issue (because the vault would open on the note that broke it 😅 , so rebooting wasn't enough 😇 )
> * Open notes in a split view 🎉 !!!
> 
> Emojis still seems to render when "they want to" in Live Preview 😊 ([#438 (comment)](https://github.com/FlorianWoelki/obsidian-iconize/issues/438#issuecomment-2042773836))
> 
> Edit: Regarding the emojis 😊 : Setting them to `None` doesn't seems to render any emojis in Live Preview while setting them to `Native` render them "once in a while" (depending on the emoji) in Live Preview...

really awesome to hear that. I am going to check out the native emoji issue. could you maybe give me some text example where it sometimes fails?

**Comment by I-Pch** [comment] 2024-04-11 16:46
@FlorianWoelki 😊 : Regarding the emojis, this is a very minimal sample I used to test the rendering 😊 

There's really nothing fancy 😄 (there's a mix of emojis and Lucide icons ) : 
(I re-wrote the "emoji names" (`:herb:`)
```markdown
:herb:
:sparkles: :LiRedo:

:LiSparkles:

> [!note]
> 
> :LiSparkles: Something 

- :purple_heart:
- :LiSparkles:


:herb: 
```
I did stumbled upon on something I think could be interesting: The emojis which can be rendered in `Live Preview` (`:sparkles:` works, for example) appear twice in `Source Mode` ... But the ones that don't get rendered in `Live Preview` appear only once in `Source Mode`

And here's a screenshot, in the 3 views, of the result I get with the small sample I shared above 😊 : 
In it, you'll see that `:purple_heart:` and `:herb:` fails to render in Live Preview while `:sparkles:` appears without issue 😊 ... 

<img width="1398" alt="Iconize - Emojis - 3 modes" src="https://github.com/FlorianWoelki/obsidian-iconize/assets/77828085/27ce410a-7043-4a85-b779-9b5019219729">

For `:purple_heart:` and `:herb:`, they seems to only appear if my cursor is on the line and if I don't have the same note opened in split views 🤷‍♀️ ... 
(That's new for me, sorry 😅 )

In the screen-recording below, instead of the emojis being rendered when I place my cursor on the line (in the note at the center), the cursor gets "longer" and there seems to be a really tiny space in place of the emoji... 

https://github.com/FlorianWoelki/obsidian-iconize/assets/77828085/c70b3286-7056-4ac6-94f4-68ab11cca23d

But if the note is in `Live Preview` and "alone", this is what I see 😊 ... 

https://github.com/FlorianWoelki/obsidian-iconize/assets/77828085/2ed2225c-4b46-43a0-99b4-63584d8926ea

I do get various mixed results depending on the number of split views open and the mode the notes are in (Source, LP, Reading)  

But at least, I can now have split views 🥳 !!!

**Comment by blooest** [comment] 2024-04-11 19:27
Seems like there's two issues in one in this thread.

Is the code in https://github.com/FlorianWoelki/obsidian-iconize/issues/438#issuecomment-2049525833 meant to fix this?
> [#438](https://github.com/FlorianWoelki/obsidian-iconize/issues/438#issuecomment-2042838878)
> 
> When Iconize is active, opening the note by clicking on the title from Explorer giving an error:
> 
> > 🔴  Failed to load "MyNote.md". Ranges must be added sorted by 'from' position and 'startSide'

Because I'm still having that issue when trying to load any notes with inlines. Oddly, one that opens on startup works perfectly, with icons, until I click off of it.

**Comment by FlorianWoelki** [comment] 2024-04-12 06:26
> Seems like there's two issues in one in this thread.
> 
> Is the code in [#438 (comment)](https://github.com/FlorianWoelki/obsidian-iconize/issues/438#issuecomment-2049525833) meant to fix this?
> 
> > [#438](https://github.com/FlorianWoelki/obsidian-iconize/issues/438#issuecomment-2042838878)
> > When Iconize is active, opening the note by clicking on the title from Explorer giving an error:
> > > 🔴  Failed to load "MyNote.md". Ranges must be added sorted by 'from' position and 'startSide'
> 
> Because I'm still having that issue when trying to load any notes with inlines. Oddly, one that opens on startup works perfectly, with icons, until I click off of it.

could you give me something that I can reproduce?

**Comment by claremacrae** [comment] 2024-04-12 21:04
In case a simple reproduction of this issue with the Tasks plugin is useful, please see https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2766#issuecomment-2052491284

**Comment by FlorianWoelki** [comment] 2024-04-12 21:09
> In case a simple reproduction of this issue with the Tasks plugin is useful, please see [obsidian-tasks-group/obsidian-tasks#2766 (comment)](https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2766#issuecomment-2052491284)

thanks. it's already fixed and I'll make a release tomorrow.

**Comment by FlorianWoelki** [comment] 2024-04-13 07:16
i've released [the version](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.10) with the fix. hopefully it is fixed now.

**Closed by FlorianWoelki** 2024-04-13 07:16 UTC
Labels: bug
