### ISSUE TITLE
Icons revert to text input on PDF Export

### ISSUE THREAD

**Issue by theaer08** [FlorianWoelki/obsidian-iconize#490] opened 2024-05-17 13:50 UTC
I'm uncertain whether this is a bug or a feature request. As it is something not working as expected, I'm filing it under the bug category. 

When Exporting to PDF, icons revert to text :hand instead of ✋ 

**To Reproduce**
1. Add some iconize icons into a note
2. Click on hamburger menu and export to PDF using native export -> results are text and not icon

**Expected behavior**
I would expect the export to "print" what I see on screen. In this case, I would expect the icon to be printed.

**Screenshots**
This shows the code in preview mode. 
![CleanShot%202024-05-17%20at%2007 42 03](https://github.com/FlorianWoelki/obsidian-iconize/assets/121214183/3ac176b9-1c18-432e-8fd1-a848a8b6e133)

This is the output using Obsidian's Export to PDF. It looks the same using Better Export plugin as well. You'll notice the icons have vanished and it is just the text remaining. 
![CleanShot 2024-05-17 at 07 48 48](https://github.com/FlorianWoelki/obsidian-iconize/assets/121214183/6b11ab88-5858-47e0-875a-71803da30115)

**Comment by theaer08** [comment] 2024-05-25 05:47
The overwhelming response led me to a different solution. 

In case someone else runs across this issue, here is what I've done:

1. Lucide.dev has a list of free icons
2. Find the icon you want to use
3. Click on "copy SVG"
4. Paste where you want the icon to appear
5. Upon Export, you'll now see your icons. 

It clutters up the edit mode.... but what the hell, at least it works. I'm not a programmer, no clue how to simplify this. But I do want to export my meeting notes to PDF and attach to emails so I can send minutes out. This worked for me. Maybe someone else can come along and figure out why the shortcakes don't convert on PDF export. But that's beyond me. SVG does the trick. 

Cheers. 
![CleanShot 2024-05-24 at 23 42 20@2x](https://github.com/FlorianWoelki/obsidian-iconize/assets/121214183/1414d491-e0d3-4fe7-8f3c-b72754f4be26)
![CleanShot 2024-05-24 at 23 43 13@2x](https://github.com/FlorianWoelki/obsidian-iconize/assets/121214183/f1f788e6-515b-4d6f-bfe0-ab65006df146)
![CleanShot 2024-05-24 at 23 44 36@2x](https://github.com/FlorianWoelki/obsidian-iconize/assets/121214183/3c943279-037d-4f45-a456-4f866662575e)

**Comment by FlorianWoelki** [comment] 2024-05-25 08:00
I think this issue a duplicate of #335

**Closed by FlorianWoelki** 2024-05-25 08:00 UTC
