### ISSUE TITLE
Icon disappears when changing file properties, and when note has file properties

### ISSUE THREAD

**Issue by DustyOldRowe** [FlorianWoelki/obsidian-iconize#375] opened 2024-02-11 00:24 UTC
When I add a file property the icon disappears, this on itself wouldn't be a problem, but if I readd it and start editing the file, the icon will vanish again.

1. Open a file
2. In the three-dot menu, add a file property
3. The icon should dissapear
4. Readd the icon, and start editing the file, writing anything
5. The icon should disappear in a few seconds

**Expected behavior**
The icon shouln't disappear when adding, editing or changing the file properties of a note.

https://github.com/FlorianWoelki/obsidian-iconize/assets/90705112/6bca5bac-9412-494e-ab0b-ae1ab2ffc9e8

**Comment by DudeThatsErin** [comment] 2024-02-24 01:59
I'm running into this one too. Was just coming here to report it but it looks like you already did.

Icons sometimes stick and other times don't. Probably not going to use this feature cause it was just a "nice to have" and not a necessity.

**Comment by rotane** [comment] 2024-02-27 21:30
Same – more or less. Although, on my end, some of the icons in the bookmarks pane disappear after using Obsidian for a little bit. I then looked into the settings and found this:
![Screenshot 2024-02-27 22 25 37](https://github.com/FlorianWoelki/obsidian-iconize/assets/19855257/75f0d65a-8825-4523-9505-a823e5028ca3)

Except for remix-icons, no icon pack has any icons in it?! Maybe this has something to do with it…

(I just updated to version 2.10.1 when this first happened.)

**Comment by rotane** [comment] 2024-02-27 21:41
Update: I removed and re-added said "empty" icon packs from the list. Now they all keep showing up as they should.

**Comment by darnocer** [comment] 2024-03-09 15:40
Same here. I thought they were disappearing randomly which may partly be the case but I was able to reproduce this issue specifically when editing properties or editing the note contents. Thanks for reporting. I use the icons for the status of things so it is a bummer that they get removed. I love this plug-in, so hope it can get fixed!

**Comment by FlorianWoelki** [comment] 2024-03-09 16:42
thank you for reporting! i am going to work on this as soon as possible!

**Comment by FlorianWoelki** [comment] 2024-03-23 09:26
This is now released with the version [v.2.11.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.0).

**Closed by FlorianWoelki** 2024-03-23 09:26 UTC
Labels: bug

**Comment by darnocer** [comment] 2024-03-23 14:03
Nice the update is working for me. Thanks @FlorianWoelki !
