### ISSUE TITLE
Plugin Disabled on Reload - Requires Update to Work

### ISSUE THREAD

**Issue by JSG-1** [FlorianWoelki/obsidian-iconize#622] opened 2024-12-02 13:26 UTC
Hi,

Thank you for creating the Iconize plugin! I’ve been experiencing an issue where every time I reload Obsidian, the plugin gets disabled, and I have to update it and manually re-enable it for it to work again.

Once I do this, the plugin functions perfectly until the next reload.

I have the core bookmarks function disabled, as I read that might be a workaround, but I still get this issue.  

The error i get in the developer console is "Plugin failure: obsidian-icon-folder Error: ENOENT: no such file or directory, open '/path/to/.obsidian/plugins/obsidian-iconize/main.js'" 

Could you please look into this? Let me know if you need any additional details about my setup!

Best regards

**Comment by FlorianWoelki** [comment] 2024-12-02 18:37
It seems like there was an issue with installing the plugin? The problem is in the path itself, and it doesn't seem to be related to an issue with Iconize itself.

I think what would be beneficial is to understand what is in your plugins directory (/path/to/.obsidian/plugins)

Closing this issue because I don't think it's an issue related to Iconize.

**Closed by FlorianWoelki** 2024-12-02 18:37 UTC
