### ISSUE TITLE
Severe performance issues with Obsidian 1.7.4

### ISSUE THREAD

**Issue by rotane** [FlorianWoelki/obsidian-iconize#602] opened 2024-10-25 10:39 UTC
**Describe the bug**
Since Obsidian updated to 1.7 a few days ago, i'm getting severe lag when typing. I've identified the culprit to be Iconize, and more precisely, when "toggle icons in links" is set to on.

When editing a note that has at least one linked file (which also shows an icon), typing has a serious delay. As soon as i disable all community plugins including Iconize, typing is practically instant. But once Iconize is present again (even if it's the only active community plugin), the input lag is back.

**Expected behavior**
Typing should be instantaneous.

**Console Infos**
Here's the console output from the Developer Console:

I click anywhere in a note:
[Violation] Forced reflow while executing JavaScript took 33ms

I type "asd":
[Violation] Forced reflow while executing JavaScript took 78ms
[Violation] Forced reflow while executing JavaScript took 72ms
[Violation] Forced reflow while executing JavaScript took 68ms

I wait and type "asd" again:
[Violation] Forced reflow while executing JavaScript took 85ms
[Violation] Forced reflow while executing JavaScript took 75ms
[Violation] Forced reflow while executing JavaScript took 68ms

I type SHIFT-POS1:
[Violation] Forced reflow while executing JavaScript took 53ms

I hit DELETE:
[Violation] Forced reflow while executing JavaScript took 117ms

I keep my finger on any button go get something like "aaaaaaaaaaaaaaaaaaaaaaa":
[Violation] Forced reflow while executing JavaScript took 85ms
[Violation] Forced reflow while executing JavaScript took 215ms
[Violation] Forced reflow while executing JavaScript took 549ms
[Violation] Forced reflow while executing JavaScript took 692ms

(Obsidian takes a good full second until it shows me "aaaaaaaaaaaaaaaaaaaaaaa")

… and so on.

**Additional context**
- I'm on Windows 10, Core i5 4440 (4× 3.1 GHz), 16 GB RAM.
- I completely uninstalled Obsidian and reinstalled it with the current installer. No change.
- Iconize Settings show "Emoji Style: Native", Icon Identifier ":", "Use icon in frontmatter: off"
- Once i toggle "icons in links" to off, typing becomes again instant.
- Turning "Toggle icons while editing notes" to off helps, but only a bit.

**Comment by rotane** [comment] 2024-10-25 11:21
I just created a test vault and found this after some tinkering: Maybe you can reproduce this when you set your Vault settings like this:
Files and Links → New link format → "Absolute Path in vault". (Then you need to update a link in your test vault/note to the new format or create a new link to test it.)

(Sidenote: Once you do this, this issue is back: #445. It appears fixed when the setting is set to the default "shortest path possible".)

**Comment by LandonSchropp** [comment] 2024-10-28 05:02
I don't have repo steps, other than it seems to be occurring within a note that has a bunch of icons, both with the `:` syntax as well as in the `icon` property of linked files.

Here's what the performance trace looks like as I'm typing:

![Screenshot 2024-10-27 at 10 00 56 PM](https://github.com/user-attachments/assets/7f572fe2-f648-4fd4-be93-f6e671eaf52a)

**Comment by arteny** [comment] 2024-11-02 09:40
reporduced for me same way, it is not possible normally edit note when Toggle icons for links is enabled. Any symbol change delays for 1 sec.

**Comment by JigenDD** [comment] 2024-11-03 03:06
This has been a HUGE problem for me as well: A longer note (1000 words+) with lots of links and/or headings with icons will result in major slowdown. And the more icons there are (which WILL happen as you add more text) the more lag there is, to the point things become unusable and you just have to deactivate Iconize.

Deactivating Iconize instantly solves the "typing lag" problem, so it is pretty clear this plugin is the problem. 

In my experience, this lag is only noticeable in notes going over the 1000-1500 word mark, and with an abundance of links (with icons) and headings (with icons). Short simple notes with a handful of links will not reveal this problem.

**Comment by wallynm** [comment] 2024-11-13 04:11
I was able to reproduce this issue, with notes very small, you only need to have duplicate several times some link with icons, and as the note have more and more of those icons, the page becomes very slow, for every icon, it becomes even slower.

**Comment by wallynm** [comment] 2024-11-13 04:25
After several tests, i've tried several older versions of Obsidian and all of them the performance issue was still present, tried disabled all icons, left only the custom ones and the slow was still going. After several trials, i've disabled my Theme (currently using "Border" theme from store) and my issue was related with my theme in the end.

Gonna try identify what's the issue with this teme and if identify something i get back here (:

**Comment by wallynm** [comment] 2024-11-13 04:35
Ok, just found out that theme "Border", there's few classes making all icons become a nightmare perf:

```
body:not(.is-mobile):has(.mod-top>.workspace-tab-header-container:hover, .titlebar-button-container:hover, .status-bar:hover) .workspace::before {
    transition: width var(--anim-out), height var(--anim-in);
}

body:not(.is-mobile):has(.workspace-ribbon.side-dock-ribbon:hover) .workspace::before {
    transition: width var(--anim-in), height var(--anim-out);
}
```

Not really sure what they're customizing, but i think while were typing those divs are updating and making a lot of calculations because of animation property.

Don't know if other users have the same issue as i, but a easy way to identify is try to disable the theme and see if generate any impact on the perf typing with icons configured. While updating CSS i've had to reload obsidian window to update CSS changes and see if the perf issues was solved while i was disabling some CSS snippets.

**Comment by vickychijwani** [comment] 2024-11-13 12:10
I have the same issue since Obsidian 1.7.x in a large note with dozens of links. I was not having issues with the _same note_ prior to Obsidian 1.7.x.

I am attaching a performance trace which clearly shows all the time is being spent recalculating styles, just as @LandonSchropp mentioned. The trace points to this piece of code as the trigger for an expensive forced reflow on every keypress: https://github.com/FlorianWoelki/obsidian-iconize/blob/14da15263501b5ba4f1179778b525ed458d9af03/src/lib/util/text.ts#L3

**Comment by Riffaells** [comment] 2024-11-20 13:12
**I have the same error**

When `"toggle icons in links"` -> is turned on, there are very strong slowdowns when changing the text, but with the value turned off everything is fine.

I have a list of links (25) leading to different notes.


The new storage failed to reproduce this problem. But also when:

- Disable all plugins except Iconize
- All callout
- Standard theme

The significant slowdown when typing remains. Most likely this is related to the theme that I have a lot of icons that are in different folders and notes.

Here's more:
![image](https://github.com/user-attachments/assets/5ff85068-a8a1-4058-8558-253afc24952f)

**Comment by mdiller** [comment] 2024-11-24 02:11
Made a PR #618  with a fix cuz this was pissing me off. Thanks to yall for your debugging.

**Comment by FlorianWoelki** [comment] 2024-11-30 10:23
I'll close this issue for now, as it seems to be fixed in the latest release! Thank you @mdiller

**Closed by FlorianWoelki** 2024-11-30 10:23 UTC
Labels: bug
