### ISSUE TITLE
Feature Request - Icons to distinguish between folder & file

### ISSUE THREAD

**Issue by Born2Root** [FlorianWoelki/obsidian-iconize#489] opened 2024-05-16 20:04 UTC
**Feature Description**
Hi,
with the standard Obsidian triangle in the nav-tree, I find it unclear to distinguish between folders and files.
Therefore I am currently using the following CSS to put a folder icon/ file icon in front of the corresponding tree sturcture.

```
/* Flat font */
/* Requires: https://github.com/Keyamoon/IcoMoon-Free/blob/master/Font/IcoMoon-Free.ttf */
.nav-folder-children .nav-file-title-content:first-child::before {
  content: "\e924  ";
  font-family: "IcoMoon-Free";
}
.nav-folder-children .nav-folder-title-content::before {
  content: "\e930  ";
  font-family: "IcoMoon-Free";
}
```

**Describe the solution you'd like**
With your add-in I am furthermore customizing the structure afterwards with custom icons, after the file/ folder icon.
Since it is getting complicated with too many addons and css files incorporating each other, I think it would be a great extension to the iconize addon.

It would be great if you could include an option to switch on/ off custom folder & file icons in the nav-tree before your iconize icons.

Thank you very much for putting effort in that great addon!

**Additional context**
The final result could look like this:

![obsidian iconize feature](https://github.com/FlorianWoelki/obsidian-iconize/assets/8644900/c95c92e1-09ee-4ddf-8c38-3f2c9b39ee3f)

**Comment by FlorianWoelki** [comment] 2024-05-25 08:08
Thank you for the feature request. I think this is a really specific addition to the plugin and will probably never be included, sorry. This is because I obviously cannot implement everything from everyone.

**Comment by alexey-skoblin** [comment] 2024-06-05 17:50
The issue is resolved by the current capabilities of the plugin.

The following line is responsible for this setting.
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/93645965/d16617ec-48c2-4ccc-a7de-e4bb7de47aa6)

General settings for folders.
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/93645965/5ba76405-f4a7-4975-be4f-aae4e885d77f)

**Comment by FlorianWoelki** [comment] 2024-06-10 07:20
> The issue is resolved by the current capabilities of the plugin.
> 
> The following line is responsible for this setting. ![image](https://private-user-images.githubusercontent.com/93645965/336949231-d16617ec-48c2-4ccc-a7de-e4bb7de47aa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDQzMDYsIm5iZiI6MTcxODAwNDAwNiwicGF0aCI6Ii85MzY0NTk2NS8zMzY5NDkyMzEtZDE2NjE3ZWMtNDhjMi00Y2NjLWE3ZGUtZTRiYjdkZTQ3YWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDA3MjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZGNmOGRjN2ZhMDUxMmJjN2FhMmI4NjI0N2UyODU1OWEyN2U4MTVmMmVjYzUxNjlkNDgzZTNmNTUwMjlhZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SgWEKJ_HJpmY6sGh3Z2Jptgr00aFCh9FrCn1EtORHIE)
> 
> General settings for folders. ![image](https://private-user-images.githubusercontent.com/93645965/336949334-5ba76405-f4a7-4975-be4f-aae4e885d77f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDQzMDYsIm5iZiI6MTcxODAwNDAwNiwicGF0aCI6Ii85MzY0NTk2NS8zMzY5NDkzMzQtNWJhNzY0MDUtZjRhNy00OTc1LWJlNGYtYWFlNGU4ODVkNzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDA3MjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZjYwMGIwZDE3NGMzNGZiYzZhN2YyZTI5ZjkyMmY1OGEzOWI4NmFhOTcyM2ZmOGFmNWE0Mzg4MjkzNWQ1MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i5K43hU3fYmMCQ66VjXLwpFZz9jb3A7BLNrMPsmQDd0)

Thank you! I'll close this issue for now.

**Closed by FlorianWoelki** 2024-06-10 07:20 UTC
Labels: enhancement
