### ISSUE TITLE
BUG: Changing "Emoji style" adds ℹ️ at the top of the note

### ISSUE THREAD

**Issue by pyxelr** [FlorianWoelki/obsidian-iconize#466] opened 2024-04-19 14:08 UTC
**Bug description**

Changing "_Emoji style_" in Iconize settings adds ℹ️ at the top of the note. It is not a serious bug, as I rather keep my emoji style consistent.

**To Reproduce**

1. Install Iconize (e.g. `v2.11.12` used in this report).
2. Being in the "Source mode" or "Live preview", modify "_Emoji style_" in Iconize settings to any other value, for example from `Native` to `Twemoji`.
3. You should observe ℹ️ emoji being placed at the top of the page.
4. The ℹ️ can be removed by reopening the page.

**Demo**

https://github.com/FlorianWoelki/obsidian-iconize/assets/30161753/664c7aa5-5d82-4f05-aa3e-82a98fb992eb

**Comment by FlorianWoelki** [comment] 2024-04-21 07:51
this has been fixed in [v2.11.13](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.13).

**Comment by pyxelr** [comment] 2024-04-21 11:28
@FlorianWoelki: Unfortunately, it does not seem entirely fixed.

In the demo, I am showing `emoji note` where I have assigned the 🍖 emoji using Iconize:

https://github.com/FlorianWoelki/obsidian-iconize/assets/30161753/198c4037-8369-4936-88f1-c6ff41d8bae7

The problem, however, so far, does not occur for pages without assigned emojis, which was the case on my previous demo.

**Comment by FlorianWoelki** [comment] 2024-04-21 14:59
> @FlorianWoelki: Unfortunately, it does not seem entirely fixed.
> 
> In the demo, I am showing `emoji note` where I have assigned the 🍖 emoji using Iconize:
> 
>  Obsidian_2024-04-21_13-22-53.mp4 
> The problem, however, so far, does not occur for pages without assigned emojis, which was the case on my previous demo.

do I understand it correctly that it is like a wrong behaving functionality between the different modes (live-preview, source mode, etc.)?

**Comment by pyxelr** [comment] 2024-04-21 15:25
> > @FlorianWoelki: Unfortunately, it does not seem entirely fixed.
> > In the demo, I am showing `emoji note` where I have assigned the 🍖 emoji using Iconize:
> > Obsidian_2024-04-21_13-22-53.mp4
> > The problem, however, so far, does not occur for pages without assigned emojis, which was the case on my previous demo.
> 
> do I understand it correctly that it is like a wrong behaving functionality between the different modes (live-preview, source mode, etc.)?

Yeah, it seems to affect "Live preview" and "Source mode". The "Reading" mode is fine.

Nevertheless, it is such a minor bug that I am fine with it. Just wanted to make you aware.

**Comment by FlorianWoelki** [comment] 2024-04-22 17:55
> > > @FlorianWoelki: Unfortunately, it does not seem entirely fixed.
> > > In the demo, I am showing `emoji note` where I have assigned the 🍖 emoji using Iconize:
> > > Obsidian_2024-04-21_13-22-53.mp4
> > > The problem, however, so far, does not occur for pages without assigned emojis, which was the case on my previous demo.
> > 
> > 
> > do I understand it correctly that it is like a wrong behaving functionality between the different modes (live-preview, source mode, etc.)?
> 
> Yeah, it seems to affect "Live preview" and "Source mode". The "Reading" mode is fine.
> 
> Nevertheless, it is such a minor bug that I am fine with it. Just wanted to make you aware.

thanks. I'll keep that in mind and fix it as soon as possible. I'll for now reopen the issue.

**Comment by FlorianWoelki** [comment] 2024-04-29 12:12
I am not sure if I can really reproduce the issue :D I am also trying to understand the problem here because when I try to change stuff from native mode to twemoji mode things work fine :D

**Comment by pyxelr** [comment] 2024-04-30 20:06
> I am not sure if I can really reproduce the issue :D I am also trying to understand the problem here because when I try to change stuff from native mode to twemoji mode things work fine :D

Unfortunately, I still can :(.

**Comment by FlorianWoelki** [comment] 2024-05-01 08:22
> > I am not sure if I can really reproduce the issue :D I am also trying to understand the problem here because when I try to change stuff from native mode to twemoji mode things work fine :D
> 
> 
> 
> Unfortunately, I still can :(.

I've did exactly the same thing you've in your video :D 

Maybe you can describe with individual steps how I can possibly reproduce it?

**Comment by pyxelr** [comment] 2024-05-02 21:23
> > > I am not sure if I can really reproduce the issue :D I am also trying to understand the problem here because when I try to change stuff from native mode to twemoji mode things work fine :D
> > 
> > 
> > Unfortunately, I still can :(.
> 
> I've did exactly the same thing you've in your video :D
> 
> Maybe you can describe with individual steps how I can possibly reproduce it?

For example:

1. Create a new folder in the root path with any name like `test`.
2. Create a new note within the folder of any name like `blabla`.
3. Right-click on the note > `Change icon` > Choose any emoji like `meat on bone`.
4. Open Iconize settings > Change "Emoji style" from `Twemoji` to `Native`.

However, I just noticed that the emoji above the note stays in the same place if I open other notes in the same tab (e.g. with left click). It is not appearing in the notes opened in a new tab (e.g. with middle click).

**Comment by FlorianWoelki** [comment] 2024-05-04 13:04
I am unfortunately not able to reproduce this :( did I do something wrong? :D 

https://github.com/FlorianWoelki/obsidian-iconize/assets/20746070/26965692-768d-4001-8e46-c53f37e893b1

**Comment by pyxelr** [comment] 2024-05-05 20:26
> I am unfortunately not able to reproduce this :( did I do something wrong? :D
> 
>  possible-issue-rec.mov

My options are a little different when I try it:

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/30161753/73341202-1f67-418b-aae3-a420169fc004)

Nevertheless, I see that when I change "Emoji style", the "Toogle icon in title" is taking action (although this option is turned off, as visible in the screenshot. The setting is not turned on by changing "Emoji style" but simply it takes action).

Also, I am noticing that emojis in your case are straight above the first letter of the note title, and in my case it is slightly shifted to the right.

**Comment by FlorianWoelki** [comment] 2024-05-07 06:56
> > I am unfortunately not able to reproduce this :( did I do something wrong? :D
> > possible-issue-rec.mov
> 
> My options are a little different when I try it:
> 
> ![image](https://private-user-images.githubusercontent.com/30161753/328046027-73341202-1f67-418b-aae3-a420169fc004.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjUyMDksIm5iZiI6MTcxNTA2NDkwOSwicGF0aCI6Ii8zMDE2MTc1My8zMjgwNDYwMjctNzMzNDEyMDItMWY2Ny00MThiLWFhZTMtYTQyMDE2OWZjMDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA2NTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ODg5NjgwNGIwZjZjNGJkZTdlY2JmOTViYjBkZWFjMWVhZjYxOGU3ZTJkMTVkNzNjY2RlYWI0MGJkZGFjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u0UBp5K19ujI8NXm0Sb8Z7fL0j_ZL-IyBnnBJcGJiO8)
> 
> Nevertheless, I see that when I change "Emoji style", the "Toogle icon in title" is taking action (although this option is turned off, as visible in the screenshot. The setting is not turned on by changing "Emoji style" but simply it takes action).
> 
> Also, I am noticing that emojis in your case are straight above the first letter of the note title, and in my case it is slightly shifted to the right.

alright, I got it. I am going to fix the icon in title behaviour for now.

**Comment by FlorianWoelki** [comment] 2024-05-09 08:20
I'll go ahead and close this issue for now. The issues with the icons in title and tabs are resolved.

**Closed by FlorianWoelki** 2024-05-09 08:20 UTC
Labels: bug

**Comment by pyxelr** [comment] 2024-05-09 22:32
I confirm that this is resolved with `2.12.0`. Great job!
