### ISSUE TITLE
Lost all Icons and Iconize Settings are not displayed

### ISSUE THREAD

**Issue by dcgk** [FlorianWoelki/obsidian-iconize#414] opened 2024-03-30 15:08 UTC
With the latest update, all the icons I had set up with Oconize disappeared.
The Settings panel is not viewable anymore. Iconize appears like a plugin with no settings.

I did briefly install Callout Manager today and deleted it again. Could this be related?

![Screenshot 2024-03-30 at 16 05 04](https://github.com/FlorianWoelki/obsidian-iconize/assets/84672793/bd703613-2592-4ce5-8072-4e59947e9cb5)

Should I delete the Iconize and reinstall it? 

Thank you in advance!

**Comment by Caotenhoch2** [comment] 2024-03-30 15:12
This is probably the same issue i described in #413

**Comment by dcgk** [comment] 2024-03-30 15:25
Thank you so much for your quick response!

I replaced the data.json file and restarted Obsidian.
Now the Iconize Settings are visible again. Inside the Settings all the rules that are specified in that data.json file. I guess I can delete these, right?

But: All my icons are gone! Do I have any chance ore restoring these somehow? I just put so much work into making everything look beautiful!

Thank you for your support in advance and thank you for creating this plugin for the community!

**Comment by Caotenhoch2** [comment] 2024-03-30 15:26
I am not the creator of the plugin, just somebody who has experienced the same issue

**Comment by dcgk** [comment] 2024-03-30 15:34
thank you Caotenhock2!
I just reviewed the Developer Console and it is giving me a whole bunch of red errors in relation to Iconize plugin. 
Will disable for now and hope for a fix.

**Comment by FlorianWoelki** [comment] 2024-03-30 16:05
hey, generally the icons are not lost. you can make sure by checking your obsidian vault directory and then going to `.obsidian/plugins/obsidian-iconize`. i'll close this issue now because it seems like a duplicate of #413.

**Closed by FlorianWoelki** 2024-03-30 16:05 UTC
