### ISSUE TITLE
Icons doesn't display on PDF 

### ISSUE THREAD

**Issue by victorNexo** [FlorianWoelki/obsidian-iconize#369] opened 2024-02-02 09:18 UTC
**Is your feature request related to a problem? Please describe.**
PDF should print the icons too, in other cases, you can use img's, but it would be cool if this feature is in the future

**Describe the solution you'd like**
I just generate a PDF from my note with icons, when the pdf prints it shows me the icons as their names.

Example:.
:fasFolder: myFolder
- :fasDatabase: Mytable
- :fasDatabase: Mytable1

**Describe alternatives you've considered**
I'm Iot sure if I have to use another pdf render or the community plugins can interact with PDF export from obsidian bc i'm a newbie at Obsidian community.

**Additional context**
I just posted this in case of someone found useful this feature and as i said before i'm not sure if plugins can interact this way with Obsidian.

**Comment by FlorianWoelki** [comment] 2024-02-03 12:44
closing due to duplicate of #335

**Closed by FlorianWoelki** 2024-02-03 12:44 UTC
