### ISSUE TITLE
After the Obsidian update, the plugin is not working.

### ISSUE THREAD

**Issue by ilya-corneli** [FlorianWoelki/obsidian-iconize#586] opened 2024-10-17 11:38 UTC
After the Obsidian update, the plugin is not working.

![image](https://github.com/user-attachments/assets/323d8f93-e77a-464b-b2ef-da793d107d89)
![image](https://github.com/user-attachments/assets/4ee956ad-f425-4a27-b708-2fba31394282)
![image](https://github.com/user-attachments/assets/6015b1c4-a8c3-405d-98ed-251f71a3eb49)

**Comment by FlorianWoelki** [comment] 2024-10-17 11:41
The first screenshot is an excalidraw error.

I am working on fixing the other two errors. This is also a duplicate of #566. So I'll close this issue for now.

**Closed by FlorianWoelki** 2024-10-17 11:41 UTC

**Comment by ilya-corneli** [comment] 2024-10-17 11:43
Thank you.
