### ISSUE TITLE
How to stop icons from changing to text form every time I click its paragraph.

### ISSUE THREAD

**Issue by albertoloscerritos** [FlorianWoelki/obsidian-iconize#504] opened 2024-06-12 03:50 UTC
Hi, hello. 
I noticed that every time I add an icon to my notes, and I click the paragraph that contains it, the icon will be converted back into text form. Like this:

![iconize](https://github.com/FlorianWoelki/obsidian-iconize/assets/16707033/86fbff16-6544-491d-99e5-ea4d10384a76)

I think it would be great to have the option to avoid this from happening. In my opinion it is kind of distracting. 
As an example, this is how icon shortcodes plugin (https://github.com/aidenlx/obsidian-icon-shortcodes) handles the use of icons in the editor:
![icon_plugin](https://github.com/FlorianWoelki/obsidian-iconize/assets/16707033/51916dfe-e367-4b0f-ae7e-7d15cdcd3942)

Hopefully you like the idea. Thanks for the great work.

**Comment by FlorianWoelki** [comment] 2024-06-15 07:46
Yes this an actually an issue. But it's a duplicate of #315.

**Closed by FlorianWoelki** 2024-06-15 07:46 UTC

**Comment by albertoloscerritos** [comment] 2024-06-17 15:43
Hi. 
Thanks for your answer. And sorry for the duplicate, I didn't know we were referring to the same issue.
Have a great monday :)

**Comment by FlorianWoelki** [comment] 2024-06-19 12:41
> Hi. Thanks for your answer. And sorry for the duplicate, I didn't know we were referring to the same issue. Have a great monday :)

Thank you :) Have a lovely rest of the week!
