### ISSUE TITLE
Certain Notes not opening or showing up

### ISSUE THREAD

**Issue by rotane** [FlorianWoelki/obsidian-iconize#424] opened 2024-04-07 08:59 UTC
I have just updated to 2.11.6 (thanks for the fix of #422!), but this introduced 2 new bugs:

- None of my DataView views show any notes now, but only blank lines.
- Certain notes don't open at all. I get this error message "Failed to load "note.md". Cannot read properties of null (reading 'replace')". (I don't see a patter, however, as to which notes won't open or why.)

As soon as i disable Iconize, all notes show up and open just fine.

I tried to manually remove the entry of "note.md" from data.json, which sadly didn't help.

**Comment by fricci** [comment] 2024-04-07 09:51
Maybe it relates to the same bug:

If the `iconize` plugin turned on, one of my note that has task query on it throws the following error:
```
plugin:dataview:15034 Uncaught TypeError: Cannot read properties of null (reading 'replace')
    at processIconInTextMarkdown (plugin:obsidian-icon-folder:5544:13)
    at eval (plugin:obsidian-icon-folder:5834:60)
    at t.render (app.js:1:1296676)
    at t.renderMarkdown (app.js:1:1295991)
    at Object.eval [as __] (plugin:dataview:15089:35)
    at w$1 (plugin:dataview:15036:3239)
    at Array.forEach (<anonymous>)
    at b (plugin:dataview:15036:1988)
```
 and

```
processIconInTextMarkdown @ plugin:obsidian-icon-folder:5544
eval @ plugin:obsidian-icon-folder:5834
t.render @ app.js:1
t.renderMarkdown @ app.js:1
eval @ plugin:dataview:15089
w$1 @ plugin:dataview:15036
b @ plugin:dataview:15036
setTimeout (async)
r @ plugin:dataview:15036
requestAnimationFrame (async)
j$1 @ plugin:dataview:15036
l$1.diffed @ plugin:dataview:15036
l$1.diffed @ plugin:dataview:15038
L$1 @ plugin:dataview:15034
x$2 @ plugin:dataview:15034
Promise.then (async)
w$2 @ plugin:dataview:15034
b$1.setState @ plugin:dataview:15034
o.__c.o.__ @ plugin:dataview:15036
refreshOperation @ plugin:dataview:15254
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
eval @ plugin:dataview:20320
l @ app.js:1
c @ app.js:1
setTimeout (async)
c @ app.js:1
plugin:obsidian-icon-folder:5544 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'replace')
    at processIconInTextMarkdown (plugin:obsidian-icon-folder:5544:13)
    at eval (plugin:obsidian-icon-folder:5834:60)
    at t.render (app.js:1:1296676)
    at t.renderMarkdown (app.js:1:1295991)
    at ui.eval (plugin:obsidian-tasks-plugin:290:6814)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-tasks-plugin:125:1370)
    at new Promise (<anonymous>)
    at L (plugin:obsidian-tasks-plugin:125:1190)
    at ui.obsidianMarkdownRenderer [as textRenderer] (plugin:obsidian-tasks-plugin:290:6673)
    at ui.eval (plugin:obsidian-tasks-plugin:290:9088)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-tasks-plugin:125:1370)
    at new Promise (<anonymous>)
    at L (plugin:obsidian-tasks-plugin:125:1190)
    at ui.renderComponentText (plugin:obsidian-tasks-plugin:290:8733)
    at ui.eval (plugin:obsidian-tasks-plugin:290:8417)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-tasks-plugin:125:1370)
    at new Promise (<anonymous>)
    at L (plugin:obsidian-tasks-plugin:125:1190)
    at ui.taskToHtml (plugin:obsidian-tasks-plugin:290:8174)
    at ui.eval (plugin:obsidian-tasks-plugin:290:7309)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-tasks-plugin:125:1370)
    at new Promise (<anonymous>)
    at L (plugin:obsidian-tasks-plugin:125:1190)
    at ui.renderTaskLine (plugin:obsidian-tasks-plugin:290:7125)
    at Lh.eval (plugin:obsidian-tasks-plugin:300:5949)
    at Generator.next (<anonymous>)
    at s (plugin:obsidian-tasks-plugin:125:1228)
```

The render of the note seems incomplete (there is no checkbox at one of the task and a lot of tasks are missing).

After I turned off iconize plugin, everything looked fine.

**Comment by Lulullia** [comment] 2024-04-07 14:12
I have the same issue here, but I have noticed that it only happens to links with an emoji in them inside callouts specifically. (Iconize v2.11.6)

This throws the same `Cannot read properties of null (reading 'replace')` error and doesn't let the note load:
```
> [!tip] [[☄️ Blog]]
```

These lines don't throw any errors:
```
> [[☄️ Blog]]
> [!tip] [[Blog]]
```

I'll just downgrade Iconize for now since there weren't any problems before. I'll come back and edit this once I find the exact version where it's working properly.

**Comment by FlorianWoelki** [comment] 2024-04-07 15:06
hey there, thanks for the bug report!

can you check out [v2.11.7](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.11.7). i am not sure if this issue is fixed within this version because i am not really able to replicate this. might this be related to the source mode (instead of live-preview mode)?

**Comment by fricci** [comment] 2024-04-07 16:35
I've tested it with 2.11.7 but the bug is still there (the line number are different from the previous log).

```
plugin:obsidian-icon-folder:5549 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'replace')
    at processIconInTextMarkdown (plugin:obsidian-icon-folder:5549:13)
    at eval (plugin:obsidian-icon-folder:5839:60)
    at t.render (app.js:1:1296676)
    at t.renderMarkdown (app.js:1:1295991)
    at ui.eval (plugin:obsidian-tasks-plugin:290:6814)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-tasks-plugin:125:1370)
    at new Promise (<anonymous>)
```

**Comment by rotane** [comment] 2024-04-07 16:35
> might this be related to the source mode (instead of live-preview mode)?

Possibly! Notes that bug out and can't be opened all contain a markdown table and at least one unicode/emoji character in them. 

When i switch to Edit mode from a "good" note and then try to open one of those problematic notes, they do open. When i then switch to Live Preview mode, the tables don't render.

**Comment by fricci** [comment] 2024-04-07 16:40
@rotane I've tested whether it depends on read/editing mode but in my case (the problem occurs if this plugin turned on + on a note contains a task query) it seems, the error occurs on both modes.

**Comment by rotane** [comment] 2024-04-07 16:46
This is the entirety of a faulty note:

```
---
Created: 2022-02-27T19:29
tags:
  - reference
  - obsidian
  - ★
---

|     |     |
| --- | --- |
| ☑ ✓ |     |
```

As soon as i remove the first checkbox, the note behaves as it should. Likewise, when i remove the table and only keep the checkbox and checkmark characters, the note also behaves normally. So it's a combination of some (?) unicode characters inside a markdown table that makes the note not render properly.

**Comment by fricci** [comment] 2024-04-07 16:52
How to reproduce:

[Problematic page with icon.md](https://github.com/FlorianWoelki/obsidian-iconize/files/14898075/Problematic.page.with.icon.md)
[Test page.md](https://github.com/FlorianWoelki/obsidian-iconize/files/14898078/Test.page.md)

The `Test page` will be broken if the plugin is turned on, works otherwise.

The problem exists regardless of the Problematic.page.with.icon has or hasn't got an icon.

Tasks plugin: 6.2.0
Iconize plugin: 2.11.7

**Comment by fricci** [comment] 2024-04-08 06:45
I've tested the functionality with 2.11.9 and it seems to be fixed, the bug has gone. 👍

**Comment by FlorianWoelki** [comment] 2024-04-08 06:47
good stuff, thank you!

**Closed by FlorianWoelki** 2024-04-08 06:47 UTC
Labels: bug

**Comment by rotane** [comment] 2024-04-08 06:48
Almost, if not for one little detail: These unicode characters i talked about now render as "null" in Live Preview mode.

But thanks for the work you put into it!

**Comment by FlorianWoelki** [comment] 2024-04-08 06:55
> Almost, if not for one little detail: These unicode characters i talked about now render as "null" in Live Preview mode.
> 
> But thanks for the work you put into it!

could you check and enable emojis as native, maybe that could work?

**Comment by FlorianWoelki** [comment] 2024-04-08 07:09
> > could you check and enable emojis as native, maybe that could work?
> 
> That's it. They were set to "none" for whatever reason. Both options (Native and Twemoji) work. Thanks again!

lovely stuff! i'll add some documentation for that.
