### ISSUE TITLE
iconize causes dataview unable to render

### ISSUE THREAD

**Issue by Ilaner2000** [FlorianWoelki/obsidian-iconize#441] opened 2024-04-11 13:51 UTC
**Describe the bug**

Enabling the "iconize" plugin causes Dataview not to display the queried content properly.

**To Reproduce**
 By enabling and disabling the iconize plugin, you will see how Dataview behaves differently. 

**Expected behavior**
Enabling the iconize shall not affect how Dataview render the result

**Comment by FlorianWoelki** [comment] 2024-04-11 13:55
closing because duplicate of #438

**Closed by FlorianWoelki** 2024-04-11 13:55 UTC
