### ISSUE TITLE
Simple Icons not loading?

### ISSUE THREAD

**Issue by pinetreemoonlight** [FlorianWoelki/obsidian-iconize#254] opened 2023-09-26 04:23 UTC
Since yesterday I cannot seem to see Simple Icons (from the predefined icon packs) in the preview. I checked the settings and it says there are zero icons loaded. I tried removing and reinstalling the icon package, but it did not work. Any ideas?

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/115622756/890ae1e3-f1a9-4bce-88b5-904b5deb1892)

**Comment by FlorianWoelki** [comment] 2023-09-26 07:37
Duplicate of #253

**Closed by FlorianWoelki** 2023-09-26 07:37 UTC
