### ISSUE TITLE
:icons: 2 <svg>icons</svg>

### ISSUE THREAD

**Issue by kfandrew910** [FlorianWoelki/obsidian-iconize#552] opened 2024-08-22 18:44 UTC
### Iconize has a problem related to exports.
When exporting to PDF it shows the text code of  the icon and not the icon as explained in #335. It is a very annoying problem for my university notes (for example) as I use a TON of icons to make them more lively, but now I don't want to go looking for the SVG tag online on every icon. I'd love to print them properly.

### Main solution
It would override the default PDF export utility so it first scans for any icons on the files and turn them into SVG tags temporally, with the user not noticing the change.

### Alternative solution
If you can't change how the default export for PDF files as it is a built-in maybe it would be possible to duplicate the file but instead of the ```:Icon:``` format, with the ```<svg>...</svg>``` format. Finally exporting the duplicate to PDF as the svg tag DOES work.

Emojis are fine, so for now I'm working with them, but I'd rather use the icon packs I have.

**Comment by FlorianWoelki** [comment] 2024-10-15 07:39
Thank you for the suggestions. I'll close this issue for now because it is a duplicate of #335.

**Closed by FlorianWoelki** 2024-10-15 07:39 UTC
