### ISSUE TITLE
Add Live Preview support

### ISSUE THREAD

**Issue by manu-romero-411** [FlorianWoelki/obsidian-iconize#281] opened 2023-10-26 23:12 UTC
This plugin is quite awesome, but it lacks Live Preview support, only showing icons while in Reading view. Live Preview support would be useful for those who don't want to rely on a constant switching between Reading view and Source view.

**Comment by FlorianWoelki** [comment] 2023-10-27 08:01
Thank you!

I think the issue is the same as #280. I'll close this here for now.

**Closed by FlorianWoelki** 2023-10-27 08:01 UTC
