### ISSUE TITLE
duplicate icon in task query output

### ISSUE THREAD

**Issue by ramnathk** [FlorianWoelki/obsidian-iconize#483] opened 2024-05-09 16:49 UTC
I have a task that mentions a 'person'. All notes of type 'person' have an icon. The task has the icon as it should, but when I query tasks, the query output has a duplicate icon
The Task itself
https://imgur.com/a/Rnk4XUe

Output of query
https://imgur.com/a/9M9Srr0

**Comment by FlorianWoelki** [comment] 2024-05-10 06:53
This seems to be a duplicate of #445. Is this correct?

**Comment by FlorianWoelki** [comment] 2024-05-21 16:30
Closing due to inactivity.

**Closed by FlorianWoelki** 2024-05-21 16:30 UTC
Labels: question
