### ISSUE TITLE
data.json in the plugins folder is modified when nothing is changed

### ISSUE THREAD

**Issue by Darkzarich** [FlorianWoelki/obsidian-iconize#565] opened 2024-09-16 16:16 UTC
**Describe the bug**
`data.json` inside `.obsidian\plugins\obsidian-icon-folder\data.json` gets modified upon starting Obsidian. 
Which results in a not working properly sync and not showing newly set icons.

**To Reproduce**

1. I set icons on my desktop Obsidian
2. Sync with a Remote Service using Remotely Save
3. Open Remove Service file system to see if the files are indeed there - I see my `data.json` for Iconize there, everything is good so far
4. Open Obsidian on my phone, sync is set to run automatically there
5. Sync is done but I see see no icons
6. Open with Total Commander phone file system to check what is going on in the folder and see `data.json` but with a different configuration in it
7. Check Remote Service again, see `data.json` file exactly the one from the phone, my desktop one with icons is gone

**Expected behavior**

`data.json` is not update when nothing is changed.

**Additional context**

It appears that my phone's Obisidian (or maybe Iconize itself I don't know exactly) is creating a new `data.json` and when syncing the remote `data.json` is considered older than the local newly created one.

So, I thought what if I just manually insert that `data.json` on my phone in the folder maybe it won't be overridden. And it worked, BUT I noticed that each time I open Obsidian on my phone the `data.json` **modification date** is updated **even though nothing is changed**. Then I try to change icons on the desktop, sync, but when I open Obsidian on my phone it gets overridden again.

**Comment by dnlbauer** [comment] 2024-11-25 23:08
Probably a duplicate of #551 ?

**Comment by Darkzarich** [comment] 2024-11-25 23:40
> Probably a duplicate of #551 ? I have the same issue..

@dnlbauer hi! I moved from obsidian-iconize to [iconic](https://github.com/gfxholo/iconic). It works much better. Hope it helps

**Closed** 2024-12-12 09:16 UTC

**Comment by giovi321** [comment] 2026-05-11 20:42
Same issue here.
