### ISSUE TITLE
Inherit Icon no longer applying to subfolder and its contents

### ISSUE THREAD

**Issue by i-report-bugs** [FlorianWoelki/obsidian-iconize#283] opened 2023-10-30 19:49 UTC
**Describe the bug**
When I updated Icon Folder to Obsidian Iconize, the subfolders stopped having the inherit icon. I have a lot of subfolders and it would really be a pain to maintain all of them individually if they don't inherit the icon properly.

**To Reproduce**
1. Right click a folder
2. Select Inherit Icon and set an icon
3. Observe how only the files get affected
4. Despair when you realize all the subfolders and their subfolders did not inherit anything and you'd have to manually set them all

**Expected behavior**
I expect the old behavior where Inherit Icon applies to subfolders too and its own subfolders etc

**Additional context**
If this is something that is intentionally done for Iconize, please just let me downgrade to the older Icon Folder.

**Comment by FlorianWoelki** [comment] 2023-10-31 07:30
This seems to be a duplicate of #205.

**Closed** 2023-10-31 07:30 UTC
Labels: duplicate

**Comment by FlorianWoelki** [comment] 2023-10-31 10:49
> @FlorianWoelki but it's already a thing that exists? It isn't a feature request, the behavior I'm describing works properly on version 2.1.2, I did some testing while waiting for a response and found out that the immediate version released after that broke it

Yes I did some explicit changes to the logic of inheritance. So it's sort of not a bug but a feature :D 
However, it seems like that it is confusing.

**Comment by FlorianWoelki** [comment] 2023-10-31 14:01
Sure yeah. There is the way of custom rules. You can enable an option for custom rules which respects the path instead of just the name of e.g., a file which is exactly what you want. I was even thinking about deprecating the inheritance functionality because by now (if I am not mistaken), you can have the same functionality of inheritance with custom rules.

**Comment by FlorianWoelki** [comment] 2023-11-09 08:04
Your rule worked fine for me. Did you use an icon or emoji? I've recently pushed a fix for updating custom rules with emojis, maybe this was the issue?

**Comment by pping** [comment] 2025-01-13 14:21
Deprecating inheritance and using regex is fine for developers, but may not be friendly to the average user。
