### ISSUE TITLE
Can't disable emoji from appearing in icon picker

### ISSUE THREAD

**Issue by keriefie** [FlorianWoelki/obsidian-iconize#592] opened 2024-10-18 11:50 UTC
**Describe the bug**
I am unable to disable emoji from appearing in the icon picker. I don't like the inconsistency of using emoji as icons (I only use Lucide icons) and would never use them, however there appears to be no way to disable it. In [the documentation](https://florianwoelki.github.io/obsidian-iconize/guide/icon-packs.html#using-emojis) there appears to be a way to set it to `None` however that does not appear to be present for me.

**To Reproduce**
1. Go to Iconize settings.
2. Find 'Emoji style'.
3. Click on dropdown.
4. No option to disable emoji, which is different from how it appears in the documentation.

**Expected behavior**
Able to disable emoji from appearing in the Icon picker.

**Screenshots**
![image](https://github.com/user-attachments/assets/ca2b2847-33ed-462a-a8c9-3f680536c63b)
![image](https://github.com/user-attachments/assets/06c3cdbf-82e0-4574-8319-0e7915d3466a)
![image](https://florianwoelki.github.io/obsidian-iconize/assets/emoji-style.q9lhFJ_X.png)

**Comment by FlorianWoelki** [comment] 2024-10-20 16:05
This is a duplicate of #525. I'll close this issue for now.

**Closed by FlorianWoelki** 2024-10-20 16:05 UTC
