### ISSUE TITLE
Emojis not displaying correctly in edit mode

### ISSUE THREAD

**Issue by perigozin** [FlorianWoelki/obsidian-iconize#477] opened 2024-05-02 13:07 UTC
**Describe the bug**
Emojis are not shown correctly in notes when the extension is enabled. They only show up when I select the line that contains the emoji. I have the latest Obsidian and Iconize extension.

**Additional context**

Obsidian version: 1.5.12
Iconize version: 2.11.14
OS: Windows 11 23H2

**Screenshots**

- Iconize enabled
![Obsidian_gQa5FtnVWz](https://github.com/FlorianWoelki/obsidian-iconize/assets/80776140/6c846a28-181a-4b5b-a93e-dc1cb3969375)

- Iconize disabled
![Obsidian_D6oEzawker](https://github.com/FlorianWoelki/obsidian-iconize/assets/80776140/9454b25c-91b5-404f-b51b-f88f1cc2db85)

- Behavior when clicked
![Obsidian_IFBFm5b6Bh](https://github.com/FlorianWoelki/obsidian-iconize/assets/80776140/a6eaee03-4eab-4fea-90d3-a02d3420b040)

**Comment by Medenor** [comment] 2024-05-02 15:27
Same problem here

**Comment by TheStalwart** [comment] 2024-05-03 05:55
I'm experiencing the same issue. 

Obsidian version: 1.5.12
Iconize version: 2.11.14
OS: MacOS Sonoma 14.4.1

Other community plugins installed:
- File Color
- Advanced Tables

**Comment by KillyMXI** [comment] 2024-05-03 18:53
Same issue.

I also observed kind of inverse issue in table cells (in new table editor):
Emojis in table cells are visible until you put cursor in the same cell.

**Comment by FlorianWoelki** [comment] 2024-05-04 13:10
thank you guys for reporting. unfortunately, I am not able to reproduce this.

are there any errors in the developer console? what theme are you guys using?

**Comment by Medenor** [comment] 2024-05-04 13:35
I use a lightly modified Obsidian Nord, but I also have the issue with the default theme, with/without enabled CSS snippets.

I don't see any error :
![CleanShot 2024-05-04 at 15 34 31](https://github.com/FlorianWoelki/obsidian-iconize/assets/60567543/bd078105-52b0-4cec-963d-e94ed7c6c214)

**Comment by KillyMXI** [comment] 2024-05-04 14:56
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/13851064/482a0ba3-0061-4dea-b487-8ad9b95d0a1d)
Seems to be loading without any complaints.
I use the default theme with some custom CSS snippets.

After some experimentation in the sandbox, looks like I experienced this behavior because I had Emoji style set to "None" in Iconize settings.
Now I'm puzzled why "None" is provided and why it was selected...

**Comment by BerserkWolfS** [comment] 2024-05-05 16:16
Hello, 

Same issue for me here, I noted that setting the Emoji style to any value other than None solved the issue as suggested @KillyMXI  and also when the setting *Toggle icons while editing notes* was deactivated. 

Here is my config:

- Obisidian: 1.5.12
- Iconize: 2.11.14
- Emoji shortcodes: 2.2.0

I also noted that the issue appeared for me when I update the Iconize plugin to the cited version. I have no idea what was the previous version number, but I think I updated it maybe last month. 
I did not noticed any errors in the console either.

I don't know if the Emoji shortcodes extension also mask them, but I am not able to add icons from icons pack, say for instance the Anvil from the rpg-awesome pack. I type :Anvil: in a file but the icon is not found. Maybe those issues are related somehow ?

**Comment by perigozin** [comment] 2024-05-05 23:37
Setting Emoji style to "Native" almost fixed it but now it has a weird glitch, one of the internal links that I showed in the first screenshots has a square symbol "■" next to it

![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/80776140/bfe92f25-c37f-42e7-bf48-8987f0fd0975)

Apparently it's rendering the "|" character as "|■" but weirdly it only happens when the internal link alias starts with "Z" (i tried every possible combination).

![Obsidian_VZvtYjpysL](https://github.com/FlorianWoelki/obsidian-iconize/assets/80776140/30ad4c35-44c8-4188-be01-c4991b1b5539)

The only solution was to disable "Toggle icons in links" (besides setting Icon style to Native).

**Comment by FlorianWoelki** [comment] 2024-05-07 06:47
ok so seems like there is some confusion around the `None` icon setting. then, I am going to consider removing it.

**Comment by KillyMXI** [comment] 2024-05-07 09:54
Alternatively, if you think it serves a good purpose to keep, it may need a better explanation within the settings UI.

**Comment by FlorianWoelki** [comment] 2024-05-10 06:54
I've decided to remove `None` in the latest update of Iconize. I'll close this issue for now. If there is any other issue, feel free to create a new issue ticket.

**Closed by FlorianWoelki** 2024-05-10 06:54 UTC
Labels: question
