### ISSUE TITLE
Automatically add icon based on tags/frontmatter

### ISSUE THREAD

**Issue by ReedWriter** [FlorianWoelki/obsidian-iconize#38] opened 2022-02-08 22:03 UTC
It would be great to have the ability to define and add an icon either by the tags a note contains or through frontmatter.

**Comment by FlorianWoelki** [comment] 2022-02-09 10:32
Lovely idea. I need to think of it. Thanks for the suggestion!

**Comment by stecydube** [comment] 2022-04-02 10:08
@ReedWriter : could the [SuperCharged Links](https://github.com/mdelobelle/obsidian_supercharged_links) plugin be what you need?

**Comment by varpness** [comment] 2022-04-09 17:00
So, for example, if a file is a png, jpg, bmp it would load a specific icon, and if the file extension was something else like md it would have a different icon? Am I understanding that correctly? I love that idea.

**Comment by Majoramari** [comment] 2023-08-18 20:55
This could be a great improvement to the plugin

**Comment by paulwalk** [comment] 2023-10-04 09:55
I understood this feature request to be to extend the existing "Custom Icon Rules" feature, which currently matches with regexes against _file names_, to also match against _tags_.

So - as an example -  a file tagged with 'idea' might be automatically assigned the icon for 'llightbulb'.

This would be useful to me in a number of contexts. For example, I would like to add an icon to the folder index document. The name of that document depends on the folder name, so this is unpredictable, but all of these documents have a tag called "index" in the frontmatter. It would be great if these showed up in the file explorer with an automatically assigned icon.

Anyway - thanks for the very useful plugin :-)

**Comment by FlorianWoelki** [comment] 2023-10-05 06:39
> I understood this feature request to be to extend the existing "Custom Icon Rules" feature, which currently matches with regexes against _file names_, to also match against _tags_.
> 
> 
> 
> So - as an example -  a file tagged with 'idea' might be automatically assigned the icon for 'llightbulb'.
> 
> 
> 
> This would be useful to me in a number of contexts. For example, I would like to add an icon to the folder index document. The name of that document depends on the folder name, so this is unpredictable, but all of these documents have a tag called "index" in the frontmatter. It would be great if these showed up in the file explorer with an automatically assigned icon.
> 
> 
> 
> Anyway - thanks for the very useful plugin :-)

Thank you! What you've described seems to be already possible in Iconize.

**Comment by paulwalk** [comment] 2023-10-05 07:48
@FlorianWoelki I can't see this functionality....?

If I tag a file with the tag `idea`, how do I select for this in the Custom Icon Rules? With other plugins, the convention is to use `#idea`, but this doesn't work.

I have tried each of these Custom Icon Rules to match files tagged with `idea`:

* `idea`
* `#idea`
* `tag:idea`
* `tag:#idea`

What am I missing?

**Comment by cyanomys** [comment] 2023-10-10 23:47
Seconding that this is a feature I really really need!

**Comment by Rhydderch** [comment] 2023-10-27 09:31
Adding my vote to this :)! In this way, icons could automatically be based on the frontmatter and iconize would be a match in heaven for people using a lot of different templates 🤝

The way I imagine it is to either support properties or have a specific property for an icon like #243, in this way the icon is note dependent on the note title.

**Comment by FlorianWoelki** [comment] 2023-10-31 08:43
This is now finally released in [v2.7.0](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.7.0).

**Closed by FlorianWoelki** 2023-10-31 08:43 UTC
Labels: enhancement

**Comment by Rhydderch** [comment] 2023-10-31 09:32
thank you 🙏

**Comment by Rhydderch** [comment] 2023-10-31 09:41
I can't seem to find the correct name for the icons.
I always get an error "icon not found".
Any tips? :)

**Comment by paulwalk** [comment] 2023-10-31 09:47
I'm also getting the "icon not found" message. Using emojis, for example looking for the icon called "calendar"

**Comment by FlorianWoelki** [comment] 2023-10-31 09:52
I need some sort of reproduction for that. For me the frontmatter property works as expected.

**Comment by FlorianWoelki** [comment] 2023-10-31 09:57
> I'm also getting the "icon not found" message. Using emojis, for example looking for the icon called "calendar"

FYI: emojis are not working atm, working on a fix. Will be probably fixed by tomorrow (see #284)

**Comment by Rhydderch** [comment] 2023-10-31 10:01
> I need some sort of reproduction for that. For me the frontmatter property works as expected.

To help me check and try to find a reproduction example, could you give me an example of what you use?
- type of frontmatter (property type)
- activated icon sets
- an example of the frontmatter with an icon set

**Comment by Rhydderch** [comment] 2023-11-01 08:46
I was able to find the correct names for the icons.
The problem was that I initially didn't know the correct names for the icons as when I typed ":" to see the shortcodes, only the ones from the "icon shortcodes" plugin showed up.
https://github.com/aidenlx/obsidian-icon-shortcodes

Once I uninstalled that plugin, I could finally find the correct names and the plugin indeed works as expected.

**Comment by danielo515** [comment] 2023-12-17 19:57
So what is the way to add icons based on tags then?

**Comment by vsxed** [comment] 2023-12-31 16:05
> So what is the way to add icons based on tags then?

---
tags: 
icon: FarSquare
---

You have to use the icon name to make it appear. Otherwise you'll get the "icon not found" error.

**Comment by vsxed** [comment] 2023-12-31 16:23
Since the feature has been merged an released, i would love to turn your attention to this issue: #321 

The implementation as of now is good, but not quite handy, since in order to get e.g. a todo-esque mechanism, you would need to enter the above to a note. The UX would be much better if tags would be supported correctly or otherwise if we could add aliases to icons (e.g. that `icon: done` would be equal to `icon: FarSquare`

**Comment by ngsilverman** [comment] 2024-01-17 16:25
Just opened a PR (https://github.com/FlorianWoelki/obsidian-iconize/pull/353) to offer a way to automatically add icons based on tags using custom rules. @paulwalk @danielo515 you guys might be interested.

Here's an example rule that would match a particular tag:
```
icontains(this.file.tags, "#my-tag")
```

**Comment by chrisgrieser** [comment] 2025-01-14 19:54
I'm a bit confused by this. If I understand several comments in this thread correctly, this issue is about setting icon rules via tags, e.g. assign `✅` to all my files that contain the tag `#done`. The issue is closed, but I cannot find how to define such a rule? The custom rules appear to only work on filename or filepaths.
