### ISSUE TITLE
The iconizer plugin dont works after update 1.7.4

### ISSUE THREAD

**Issue by MoonlightFemboy** [FlorianWoelki/obsidian-iconize#596] opened 2024-10-20 03:20 UTC
The aplication dont work more after the update all my icons was deleted from my files and an conection error between the folders are happening(looks like)

Nothing works if i try to add any icon its deleted when reloading the app.

![Screenshot_20241020_000754_Obsidian](https://github.com/user-attachments/assets/7ea270e8-a6f6-4a47-99b6-11752cbd2de2)

Just have this print, but ourhers message that apper was something like "failed to load plugin Iconizer" and outher saying failure too.

Please help ICONIZER IS LITERALY VITAL TO ME
Or ocd will kill me. . .

**Comment by kitschpatrol** [comment] 2024-10-20 04:53
Something's undefined that probably shouldn't be. Temporary fix in #597.

**Comment by rubcap** [comment] 2024-10-20 10:30
I get the same error message upon loading Obsidian 1.7.4

Icons that I added to folders and notes aren't loaded on start-up. When I switch from the Explorer tab to the Bookmarks tab and back, the icons suddenly appear.

**Comment by bwoah-md** [comment] 2024-10-20 13:02
Same problem here

**Comment by techeddie** [comment] 2024-10-20 13:44
having the same issue

**Comment by FlorianWoelki** [comment] 2024-10-20 16:04
This is a duplicate of #566. I'll close this issue for now. I'm probably releasing tomorrow a new version with the fix.

**Closed by FlorianWoelki** 2024-10-20 16:04 UTC
